from loguru import logger


class LogsExtractor:
    """Responsible for parsing logs from server"""

    @staticmethod
    def extract_uuid_and_name(clean_line: str) -> tuple[str, str]:
        """Extracts UUID and user_name from log

        Args:
            clean_line: Log from server
        Returns:
            UUID and user_name"""

        # [20:29:50 INFO]: UUID of player Name123 is 7d2ce94b-2800-33ba-b6b6-d52f93375d0f
        try:
            message_itself = clean_line.split("]: ")[-1]
            # UUID of player Name123 is 7d2ce94b-2800-33ba-b6b6-d52f93375d0f

            user_uuid = message_itself.split(' is ')[-1].strip()
            # 7d2ce94b-2800-33ba-b6b6-d52f93375d0f

            left_part = message_itself.split(' is ')[0]
            # [20:29:50 INFO]: UUID of player Name123
            user_name = left_part.split(' player ')[-1].strip()
            # Name123

            return user_uuid, user_name

        except Exception as e:
            logger.exception(e)
            return '', ''

    @staticmethod
    def extract_user_name(clean_line: str) -> str:
        """Extracts UserName from server's output

        Args:
            clean_line: Output from server
        Returns:
            UserName"""

        # Step A: Get everything after the Minecraft log prefix "]: "
        # This leaves us with: "Name[/188.126.89.172:58488] logged in..."
        after_prefix = clean_line.split("]: ")[-1]

        # Step B: Get everything before the IP bracket "[/"
        # This leaves us with: "Name"
        username = after_prefix.split("[/")[0]

        # Step C: Clean any accidental whitespace
        username = username.strip()

        return username

    @staticmethod
    def extract_login_coords_and_ip(clean_line: str) -> tuple[str, str]:
        """Extracts login coordinates and IP address

        Args:
            clean_line: Line from log of the server to extract data from
        Returns:
            Login coordinates and IP address or empty strings, in case failed parsing"""

        # [16:25:44 INFO]: random12[/127.0.0.1:58799] logged in with entity id 1 at ([world_1]5556.5, 87.0, -4584.5)
        try:
            after_prefix = clean_line.split("]: ")[-1]
            # random12[/127.0.0.1:58799] logged in with entity id 1 at ([world_1]5556.5, 87.0, -4584.5)

            right_part = after_prefix.split('logged in with entity id')[-1]
            # 1 at ([world_1]5556.5, 87.0, -4584.5)

            coords_with_world = right_part.split('at ')[-1]
            # ([world_1]5556.5, 87.0, -4584.5)

            coords_with_bracket = coords_with_world.split(']')[-1].strip()
            # 5556.5, 87.0, -4584.5)

            coords = coords_with_bracket.replace(')', '')
            # 5556.5, 87.0, -4584.5

            after_prefix = clean_line.split("]: ")[-1]
            # random12[/127.0.0.1:58799] logged in with entity id 1 at ([world_1]5556.5, 87.0, -4584.5)

            left_part = after_prefix.split('] ')[0]
            # random12[/127.0.0.1:58799

            ip_address_with_port = left_part.split('[/')[-1].strip()
            # 127.0.0.1:58799

            if ':' in ip_address_with_port:
                ip_address = ip_address_with_port.split(':')[0].strip()
                # 127.0.0.1:58799
            else:
                ip_address = ip_address_with_port

            return coords, ip_address
        except Exception as e:
            logger.exception(e)
            return '', ''

    @staticmethod
    def extract_updated_coords(clean_line: str) -> tuple[str, str]:
        """Extracts current Player's coordinates, which were generated by tp-command

        Notes:
            Tp, that generated this log, was made from the same place to the same place, so Player did not notice
            it in any ways, even if was running
        Args:
            clean_line: Log from server
        Returns:
            Coordinates and user_name, extracted from log"""

        # [13:32:32 INFO]: Teleported Name123 to 5556.500000, 87.000000, -4584.500000'
        try:
            coords = clean_line.split(' to ')[-1].strip()
            # 5556.500000, 87.000000, -4584.500000

            user_name = clean_line.split(' to ')[0].split(' Teleported ')[-1].strip()
            # Name123

            return coords, user_name
        except Exception as e:
            logger.exception(e)
            return '', ''

    @staticmethod
    def parse_coordinates(coords_str: str) -> tuple[int, int, int]:
        """Parses string with 3 coordinates into 3 numbers

        Args:
            coords_str: string with coordinates
        Returns:
            x, y, z"""

        # Initial string: "5557.332153545321, 87.0, -4582.1460532785395"
        x, y, z = coords_str.split(' ')

        x = x.replace(',', '')
        y = y.replace(',', '')
        z = z.replace(',', '')

        x = int(float(x))
        y = int(float(y))
        z = int(float(z))

        return x, y, z
